namespace ESign.API.Infrastructure.Entities;

// ESignProviderConfig maps to one row in the esign_providers table
// Dapper uses column names (with MatchNamesWithUnderscores = true) to map DB columns to these properties
// provider_base_url → ProviderBaseUrl, encrypted_api_key → EncryptedApiKey, etc.
public class ESignProviderConfig
{
	public long Id { get; set; }   // Primary key — auto-generated by DB
	public string ProviderName { get; set; } = string.Empty;   // e.g. "SignDeskSandbox", "MockProvider"
	public string ProviderBaseUrl { get; set; } = string.Empty;   // e.g. "https://uat.SignDesk.in"
	public string ProviderEndpoint { get; set; } = string.Empty;   // e.g. "/api/sandbox/signRequest"
	public string? EncryptedApiKey { get; set; }                   // AES-encrypted API key — decrypted before use
	public string? RequestHeadersJson { get; set; }                   // JSON of extra headers e.g. x-parse-application-id
	public int MaxRetryAttempts { get; set; } = 3;              // How many times to retry before failover
	public int Priority { get; set; }                   // Lower = higher priority (1 runs first)
	public bool IsActive { get; set; } = true;           // Only active providers are used
	public bool WebhookSupported { get; set; } = true;           // Does this provider support webhook callbacks?
}