namespace ESign.API.Infrastructure.Entities
{

	public class ESignProviderConfig
	{
		public long Id { get; set; }   // Primary key — auto-generated by DB
		public string ProviderName { get; set; } = string.Empty;
		public string ProviderBaseUrl { get; set; } = string.Empty;
		public string ProviderEndpoint { get; set; } = string.Empty;
		public string? EncryptedApiKey { get; set; }
		public string? RequestHeadersJson { get; set; }
		public int MaxRetryAttempts { get; set; } = 3;
		public int Priority { get; set; }
		public bool IsActive { get; set; } = true;
		public bool WebhookSupported { get; set; } = true;
	}
}